import {burgerButton} from './mobile/burger-button.js';
import {filterBar} from './mobile/filter-bar.js';
import {tabBar} from './mobile/tab.js';
import {sumeRest} from './mobile/sume-rest.js';
import {notify} from './mobile/notify.js';
import {form} from './mobile/form.js';
import {renderCkeditor} from './mobile/ckeditor.js';
import {renderFaqs} from './mobile/faqs.js';
import {renderSelects} from './mobile/select.js';
import {imageContent} from './mobile/image-content.js';

burgerButton();
filterBar();
tabBar();
sumeRest();
notify();
form();
renderCkeditor();
renderFaqs();
renderSelects();
imageContent();
